version: "3.2"


services:
  database:
    restart: always
    image: mysql/mysql-server:latest
    ports:
      - 3307:3307
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root


volumes:
  mysql-datavolume:
    driver: local
